name: Simpleworkdflow
on : workflow_dispatch
jobs:
  firstJob :
   runs-on: ubuntu-latest
   steps:
   - name : Dont print match
     run: |
          echo "Repository Name: ${{ github.repository }}"
          if ${{ contains(github.repository, 'actions') }}; then
            echo "Match"
          fi

   - name: print match 
     run: |
            if ${{ contains(github.repository, 'actions') }}; then
            echo "Match"
            fi
