name: Simpleworkdflow
on : workflow_dispatch
jobs:
  firstJob :
   runs-on: ubuntu-latest
   steps:
   - name : Dont print match
     run: |
         if [ Contains("abcd" == "abc") ]; then
            echo "Match"
          fi
   - name : print match 
     run: |
        if [ Contains("abcd" == "abcd") ]; then
            echo "Match"
          fi
     
