name: Simpleworkdflow
on : workflow_dispatch
jobs:
  firstJob :
   runs-on: ubuntu-latest
   steps:
   - name : Dont print match
     run: |
      if ("abcd" == "abc")
        echo "Match"
   - name : print match 
     run: |
      if ("abcd" == "abcd")
        echo "Match"
     
